# Generated by Django 2.0.2 on 2018-03-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_slidepagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidepage',
            name='align',
            field=models.CharField(choices=[('cl', 'center-left'), ('cr', 'center-right'), ('fl', 'full-left'), ('fr', 'full-right')], default='cl', max_length=2),
        ),
    ]
