# Generated by Django 2.0.2 on 2018-03-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=55)),
                ('org', models.CharField(max_length=255, verbose_name='organisation')),
                ('org_url', models.URLField(blank=True, verbose_name='organisation url')),
            ],
        ),
    ]
