# Generated by Django 2.0.2 on 2018-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_code',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
