# Generated by Django 2.0.2 on 2018-03-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='motto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
