# Generated by Django 2.0.2 on 2018-03-09 15:55

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sectionpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionpage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='position',
            field=models.IntegerField(default=home.models.new_position),
        ),
    ]
