# Generated by Django 2.0.2 on 2018-03-10 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180309_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidePage',
            fields=[
                ('sectionpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.SectionPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.sectionpage',),
        ),
    ]
