# Generated by Django 2.0.2 on 2018-03-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_slidepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='motto',
            field=models.CharField(default='', max_length=255),
        ),
    ]
