# Generated by Django 2.0.2 on 2018-03-19 15:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180317_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_sections', to='home.HomePage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.SectionPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
