# Generated by Django 2.0.2 on 2018-03-20 10:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_slidepagegalleryimage'),
        ('sections', '0002_sectionpagegalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPageSlides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('section', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_slides', to='sections.SectionPage')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='slides.SlidePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
